void fun2(){
	throw new Exception("FAILED!");
}

fun2();